---
  - hosts: all
    become: yes
    gather_facts: yes

    tasks:

      # # Added in 2.8
      # - name: generate ssh key for VM
      #   openssh_keypair:
      #     path: ./id_ssh_rsa

      - name: copy ssh key to VM
        authorized_key:
          user: "{{ssh_username}}"
          key: "{{ lookup('file','../id_ssh_rsa.pub') }}"

      - name: add docker repo key
        apt_key:
          url: "https://download.docker.com/linux/ubuntu/gpg"
          id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"

      - name: add docker repo
        apt_repository:
          repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"


      - name: install docker and etcd
        apt:
          name: "{{ packages }}"
          state: present
          update_cache: yes
        vars:
          packages:
            - docker-ce
            - docker-ce-cli
            - containerd.io
            - etcd

      - name: Add user to "docker" group
        user:
          name: "{{ ssh_username }}"
          groups: "docker"
          append: true


      - name: download rke binary
        get_url:
          dest: ~/rke 
          url: https://github.com/rancher/rke/releases/download/{{ rke_version }}/rke_linux-amd64
          mode: 0644

      - name: copy cluster.yaml
        copy:
          src: ../rke/cluster.yaml
          dest: ~/cluster.yaml
          owner: "{{ ssh_username }}"


      - name: bootsrap the cluster using rke
        shell: ~/rke up


      - name: copy kube_config file to host running packer
        copy:
          src: ~/kube_config_cluster.yml
          dest: ../kube_config_cluster.yml
          remote_src: yes