---
  - hosts: all
    become: yes
    gather_facts: yes

    tasks:

      # # Added in 2.8
      # - name: generate ssh key for VM
      #   openssh_keypair:
      #     path: ./id_ssh_rsa

      - name: modprobe - load kernel modules
        modprobe:
          name: {{ kernel_modules }}
          state: present 
        vars:
          kernel_modules:
            - br_netfilter
            - ip6_udp_tunnel
            - ip_set
            - ip_set_hash_ip
            - ip_set_hash_net
            - iptable_filter
            - iptable_nat
            - iptable_mangle
            - iptable_raw
            - nf_conntrack_netlink
            - nf_conntrack
            - nf_conntrack_ipv4
            - nf_defrag_ipv4
            - nf_nat
            - nf_nat_ipv4
            - nf_nat_masquerade_ipv4
            - nfnetlink
            - udp_tunnel
            - veth
            - vxlan
            - x_tables
            - xt_addrtype
            - xt_conntrack
            - xt_comment
            - xt_mark
            - xt_multiport
            - xt_nat
            - xt_recent
            - xt_set
            - xt_statistic
            - xt_tcpudp


      - name: copy ssh key to VM
        authorized_key:
          user: "{{ssh_username}}"
          key: "{{ lookup('file','../id_ssh_rsa.pub') }}"

      - name: add docker repo key
        apt_key:
          url: "https://download.docker.com/linux/ubuntu/gpg"
          id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"

      - name: add docker repo
        apt_repository:
          repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"


      - name: install docker and etcd
        apt:
          name: "{{ packages }}"
          state: present
          update_cache: yes
        vars:
          packages:
            - docker-ce
            - docker-ce-cli
            - containerd.io
            - etcd

      - name: Add user to "docker" group
        user:
          name: "{{ ssh_username }}"
          groups: "docker"
          append: true


      - name: download rke binary
        get_url:
          dest: ~/rke 
          url: https://github.com/rancher/rke/releases/download/{{ rke_version }}/rke_linux-amd64
          mode: 0744
          owner: "{{ ssh_username }}"

      - name: copy cluster.yaml
        copy:
          src: ../rke/cluster.yaml
          dest: ~/cluster.yaml
          owner: "{{ ssh_username }}"


      - name: bootsrap the cluster using rke
        shell: ~/rke up


      - name: copy kube_config file to host running packer
        copy:
          src: ~/kube_config_cluster.yml
          dest: ../kube_config_cluster.yml
          remote_src: yes